name: Run test cases

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
       
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Test with Vitest
        run: pnpm test:coverage